name: Bug Report
description: Create a report to help us improve
title: "[bug]: "
labels:
  - bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    attributes:
      label: Build/Project URL
      description: URL to project/build that issue is about (make sure you set Public builds setting for the project)
      placeholder: https://console.nativeci.io/project/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
